OpenQASM 3.0;
include "stdgates.inc";
bit[4] bits;
qubit[4] qubits;
reset qubits[0];
reset qubits[1];
reset qubits[2];
reset qubits[3];
h qubits[0];
h qubits[1];
h qubits[2];
h qubits[3];
cx qubits[1], qubits[0];
rz(0.7) qubits[0];
cx qubits[1], qubits[0];
cx qubits[3], qubits[0];
rz(0.7) qubits[0];
cx qubits[3], qubits[0];
cx qubits[2], qubits[1];
rz(0.7) qubits[1];
cx qubits[2], qubits[1];
cx qubits[3], qubits[2];
rz(0.7) qubits[2];
cx qubits[3], qubits[2];
h qubits[0];
rz(2.6) qubits[0];
h qubits[0];
h qubits[1];
rz(2.6) qubits[1];
h qubits[1];
h qubits[2];
rz(2.6) qubits[2];
h qubits[2];
h qubits[3];
rz(2.6) qubits[3];
h qubits[3];
bits[0] = measure qubits[0];
bits[1] = measure qubits[1];
bits[2] = measure qubits[2];
bits[3] = measure qubits[3];