OPENQASM 3.0;
include "stdgates.inc";
bit[8] bits;
qubit[8] qubits;
reset qubits[0];
reset qubits[1];
reset qubits[2];
reset qubits[3];
reset qubits[4];
reset qubits[5];
reset qubits[6];
reset qubits[7];
h qubits[0];
h qubits[1];
h qubits[2];
h qubits[3];
h qubits[4];
h qubits[5];
h qubits[6];
h qubits[7];
cx qubits[2], qubits[1];
rz(2.6) qubits[1];
cx qubits[2], qubits[1];
cx qubits[4], qubits[1];
rz(2.6) qubits[1];
cx qubits[4], qubits[1];
cx qubits[5], qubits[1];
rz(2.6) qubits[1];
cx qubits[5], qubits[1];
cx qubits[6], qubits[1];
rz(2.6) qubits[1];
cx qubits[6], qubits[1];
cx qubits[6], qubits[2];
rz(2.6) qubits[2];
cx qubits[6], qubits[2];
cx qubits[7], qubits[2];
rz(2.6) qubits[2];
cx qubits[7], qubits[2];
cx qubits[5], qubits[3];
rz(2.6) qubits[3];
cx qubits[5], qubits[3];
cx qubits[7], qubits[3];
rz(2.6) qubits[3];
cx qubits[7], qubits[3];
cx qubits[5], qubits[4];
rz(2.6) qubits[4];
cx qubits[5], qubits[4];
h qubits[0];
rz(6.2) qubits[0];
h qubits[0];
h qubits[1];
rz(6.2) qubits[1];
h qubits[1];
h qubits[2];
rz(6.2) qubits[2];
h qubits[2];
h qubits[3];
rz(6.2) qubits[3];
h qubits[3];
h qubits[4];
rz(6.2) qubits[4];
h qubits[4];
h qubits[5];
rz(6.2) qubits[5];
h qubits[5];
h qubits[6];
rz(6.2) qubits[6];
h qubits[6];
h qubits[7];
rz(6.2) qubits[7];
h qubits[7];
bits[0] = measure qubits[0];
bits[1] = measure qubits[1];
bits[2] = measure qubits[2];
bits[3] = measure qubits[3];
bits[4] = measure qubits[4];
bits[5] = measure qubits[5];
bits[6] = measure qubits[6];
bits[7] = measure qubits[7];
